# Generated by Django 3.2.25 on 2025-12-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='summary',
            new_name='description',
        ),
    ]
